### PR TITLE
Simplify the marker parsing logic

### PR DESCRIPTION
**Pull request by terminalmage**
Refs: https://github.com/saltstack/salt/pull/46503

### CODE REVIEW

**Comment by psyer** [comment]
We are ok with this code, but it will break backward compatibility with the following situation.  If a service account has login disabled e.g they are not listed in /etc/security/access.conf (our example is mysql) getting the environment returns "cannot open session" and does not return an environment.  The current code lets this pass through and the eventual setuid does work to run the command. The code in the pull request will block this and throw an exception. This could cause existing usage to fail.

The latest pull request today handles this situation by allowing both markers to be missing, but logging an error when it happens.

**Comment by psyer** [comment]
In /etc/security/access.conf you can list users and what accesses they are allowed, such as login access. Our system only allows logins for a small set of users, in particular the mysql user exists, but is not allowed to go through the PAM login sequence. When the salt code that tries to gather the env runs sudo/su, PAM rejects this attempt and writes 'cannot open session' to stderr. The python snippit to get the env is not run, so the marker count is zero. 

However later on in the code where timed_subprocess is called the setuid does not go through PAM and is allowed.

The existing salt infrastructure allows you to run a command as a nologin user, albeit without an env. Your updated code will prevent this and we are concerned it may break the way this is currently working.  The question is how do you want to handle this situation? Do you want to continue to allow this usage pattern or is this a hole that you want to close?

**Comment by terminalmage** [comment]
I don't see any issues with preserving that old behavior. I've updated this PR to log an error when the marker count is 0. What do you think?

**Comment by psyer** [comment]
That looks perfect. Merged.

**Pull request merged**
